apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: {{ .Values.appImage }}
        name: webserver
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_PASSWORD
          value: admin123
        - name: MYSQL_DATABASE
          value: araba_kiralama
        - name: MYSQL_DATABASE_HOST
          value: mysql
        - name: MYSQL_USER
          value: admin
          





        resources:
            limits:
              cpu: 100m
            requests:
              cpu: 80m
        

