apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  type: NodePort
  #type: LoadBalancer
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: {{ .Values.appService.nodePort }}
  selector:
    app: webserver

