apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  # type: LoadBalancer
  # type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30008