apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: redis
        image: redis:6-alpine
        ports:
        - containerPort: 6379
        env:
          - name: redis-service
            value: redis
      #   volumeMounts:
      #     - name: redis-db
      #       mountPath: /usr/local/etc/redis
      # volumes:
      #   - name: redis-db
      #     persistentVolumeClaim:
      #       claimName: redis-pvc
--- 
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379