apiVersion: v1
kind: Service
metadata:
  labels:
    app: kittens
  name: kittens
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30004
  selector:
    app: kittens
