apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver
  name: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - image: aydintokuslu/resultserver2025:2.0
        name: resultserver
        # ports:
        # - containerPort: 80
        env:
        - name: MYSQL_DATABASE_HOST 
          value: mysql
        - name: MYSQL_DATABASE
          value: phonebook
        - name: MYSQL_USER
          value: clarus
        - name: MYSQL_PASSWORD
          value: Clarusway_1
        resources: {}