apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: aydintokuslu/webserver2025:2.0
        name: webserver
        # ports:
        # - containerPort: 80
        env:
        - name: MYSQL_DATABASE_HOST 
          value: mysql
        - name: MYSQL_DATABASE
          value: phonebook
        - name: MYSQL_USER
          value: clarus
        - name: MYSQL_PASSWORD
          value: Clarusway_1
        resources: {}