apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookstore
  name: bookstore
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007
  selector:
    app: bookstore

