apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: R1234r
        - name: MYSQL_DATABASE
          value: bookstore_db
        - name: MYSQL_USER
          value: clarusway
        - name: MYSQL_PASSWORD
          value: Clarusway_1
      #   volumeMounts:
      #   - name: mysql-pv-volume
      #     mountPath: /var/lib/mysql
      #   resources: {}
      # volumes:
      # - name: mysql-pv-volume
      #   persistentVolumeClaim:
      #     claimName: mysql-pv-claim
