apiVersion: v1
kind: Service
metadata:
  labels:
    app: roman
  name: roman
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30005
  selector:
    app: roman
